services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend
    command: sh -c "npm run dev -- --host 0.0.0.0"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
    depends_on:
      - db
    command: sh -c "until nc -z db 1433; do echo 'Waiting for db...'; sleep 1; done; python scripts/create_db.py && python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data


volumes:
  node_modules:
  db_data:
