# Generated by Django 5.2.8 on 2026-02-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0002_user_password_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stores', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserStores',
                'unique_together': {('user', 'store')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, through='users.UserStore', to='stores.store', verbose_name='Tiendas'),
        ),
    ]
