# Generated by Django 5.2.8 on 2025-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_middle_name_remove_user_second_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=list, verbose_name='Permisos'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
