# Generated by Django 5.2.8 on 2026-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Prices',
                'ordering': ['-registration_date'],
            },
        ),
    ]
