# Generated by Django 5.2.8 on 2026-01-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prices', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'store', 'effective_date')},
        ),
    ]
