# Generated by Django 5.2.8 on 2025-12-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_price_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-registration_date']},
        ),
    ]
