# Generated by Django 5.2.8 on 2026-02-10 21:37

import apps.stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.IntegerField(unique=True, validators=[apps.stores.models.validate_positive_number]),
        ),
    ]
