# Generated by Django 5.2.8 on 2026-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
