# Generated by Django 5.2.8 on 2026-01-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.brand')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subgroup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.producttype')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
