# Generated by Django 5.2.7 on 2025-11-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('subgroup', models.CharField(max_length=100)),
            ],
        ),
    ]
