# Generated by Django 5.2.7 on 2025-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_product_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
